
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import MainNav from '@/components/main-nav'
import { ThemeProvider } from "@/components/theme-provider"
import { Sidebar } from '@/components/sidebar'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import { options } from '../api/auth/[...nextauth]/options'
import Provider from './(context)/client-provider'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options);
  if (!session) {
    redirect("/signin")
  }
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider session={session}>
            <div className='flex flex-col h-screen'>
              <MainNav />
              <div className='flex flex-1 flex-row overflow-hidden'>
                <Sidebar />
                {children}
              </div>
            </div>
            <Toaster />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
