
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import MainNav from '@/components/main-nav'
import { ThemeProvider } from "@/components/theme-provider"
import { Sidebar } from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className='flex flex-col h-screen'>
            <MainNav />
            <div className='flex flex-1 flex-row overflow-hidden'>
              <Sidebar/>
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
